### PR TITLE
feat(charts): add optional syslog endpoint setting

### PR DESCRIPTION
**Pull request by rimusz**
replaces PR #72 which got too messy to read

### CODE REVIEW

**Comment by rimusz** [comment]
@kmala @bacongobbler would you mind to take a look, please, thanks

**Comment by bacongobbler** [comment]
If you wouldn't mind amending your commit such that it follows the [commit style guide](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style), that would be awesome! That way it'll get picked up by `deisrel` when we generate the release changelog. Thanks!

**Comment by rimusz** [comment]
@bacongobbler done

**Comment by bacongobbler** [comment]
Would you mind squashing your commits together?

**Comment by rimusz** [comment]
@bacongobbler squashing can be done on pressing `Squash and merge` butoon

**Comment by mboersma** [comment]
LGTM2, but it would be great if @kmala could also review this.

**Review by kmala — APPROVED** [review]

**Pull request merged**
