### PR TITLE
fix(elastic search): Allow the elastic search plugin to index via namespace

### PR DESCRIPTION
**Pull request by jchauncey**
You can provide the elastic search plugin a path to look for a value to use as the index name such as . However, if you do this you cant append a logstash style dateformat on the end of the index name which helps with archiving old log data. So we are going to monkey patch the plugin to provide this functionality until the pull request is accepted.

### CODE REVIEW

**Comment by sstarcher** [comment]
Can we turn - ELASTICSEARCH_LOGSTASH_FORMAT on by default.  I can't imagine it not being preferable for all users of elasticsearch.

**Comment by sstarcher** [comment]
Only setting 

```
          - name: ELASTICSEARCH_LOGSTASH_FORMAT
            value: "true"
```

I still get my logs into the fluentd index.

**Comment by jchauncey** [comment]
are you using the image from #59

**Comment by sstarcher** [comment]
@jchauncey  yep - `image: quay.io/deisci/fluentd:git-a89dfce`

**Comment by sstarcher** [comment]
Below is the config that is output.  I also get the following message in the log.
`2016-10-19 15:11:45 +0000 [warn]: section <parse> is not used in <store> of elasticsearch plugin`

```
<store>
      @type "elasticsearch"
      time_key_format ""
      time_key ""
      time_key_exclude_timestamp
      logstash_prefix "logstash"
      index_name "fluentd"
      include_tag_key false
      target_index_key ""
      target_type_key ""
      host "elasticsearch-logging"
      port 9200
      scheme "http"
      buffer_type "memory"
      buffer_chunk_limit 8m
      buffer_queue_limit 8192
      flush_interval 10s
      retry_limit 10
      disable_retry_limit
      retry_wait 1s
      max_retry_wait 60s
      num_threads 1
      logstash_format true
      <buffer>
        flush_mode interval
        retry_type exponential_backoff
        @type memory
        flush_thread_count 1
        flush_interval 10s
        retry_forever
        retry_max_times 10
        retry_max_interval 60s
        chunk_limit_size 8m
        queue_length_limit 8192
      </buffer>
      <parse>
        time_key
      </parse>
      <inject>
        time_key
      </inject>
    </store>
```

**Comment by jchauncey** [comment]
im working on fixing that config file let me see if my changes will help you

**Comment by jchauncey** [comment]
@sstarcher try `git-f113aac` give it a few minutes to build but this should help

**Comment by sstarcher** [comment]
@jchauncey looks like git-f113aac is working

**Pull request merged**
