### PR TITLE
fix: Undo storing syslog details in global var

### LINKED ISSUE #75: duplicate logs from deis apps:logs
After deploying workflow-beta4, I found that I saw duplicate logs for everything:

```
><> deis logs
INFO [go]: bacongobbler created initial release
INFO [go]: domain go added
INFO [go]: bacongobbler created initial release
INFO [go]: domain go added
INFO [go]: bacongobbler deployed 779ca3d
INFO [go]: bacongobbler deployed 779ca3d
go-v2-web-wusof -- 2016/05/10 20:10:47 Successfully copied home/go:git-779ca3d7/push/slug.tgz to slug.tgz
go-v2-web-wusof -- 2016/05/10 20:10:47 listening on 5000...
go-v2-web-wusof -- 2016/05/10 20:10:47 Successfully copied home/go:git-779ca3d7/push/slug.tgz to slug.tgz
go-v2-web-wusof -- 2016/05/10 20:10:47 listening on 5000...
go-v2-web-wusof -- 2016/05/10 20:11:24 10.246.25.7 GET /
go-v2-web-wusof -- 2016/05/10 20:11:24 10.246.25.7 GET /
go-v2-web-wusof -- 2016/05/10 20:12:39 10.246.25.1 GET /
go-v2-web-wusof -- 2016/05/10 20:12:39 10.246.25.1 GET /favicon.ico
go-v2-web-wusof -- 2016/05/10 20:12:39 10.246.25.1 GET /
go-v2-web-wusof -- 2016/05/10 20:12:39 10.246.25.1 GET /favicon.ico
```

### PR DESCRIPTION
**Pull request by jchauncey**
fixes https://github.com/deis/logger/issues/75
Trying to outsmart fluentd I ended up causing messages to be sent twice and sometimes three times

### CODE REVIEW

**Comment by jchauncey** [comment]
To test do

```
DEIS_REGISTRY=quay.io/ IMAGE_PREFIX=jchauncey make build push upgrade
deis create <app>
deis logs
```

You should only see 1 log line per message

**Comment by bacongobbler** [comment]
works for me!

**Comment by vdice** [comment]
I still get duplicates on latest version of this PR (this was after the make steps mentioned above):

```
vaughndice in fluentd on (jchauncey-undo-global-logger) $ deis create
Creating Application... done, created quartz-electron
Git remote deis added
remote available at ssh://git@deis-builder.104.197.166.44.nip.io:2222/quartz-electron.git
vaughndice in fluentd on (jchauncey-undo-global-logger) $ deis logs
INFO [quartz-electron]: v created initial release
INFO [quartz-electron]: v created initial release
INFO [quartz-electron]: domain quartz-electron added
INFO [quartz-electron]: domain quartz-electron added
```

**Comment by bacongobbler** [comment]
I just re-tested this PR again. Still no duplicate logs. @vdice can you check and verify that the git tag of your fluentd pod matches the commit here? I have `git-ad48f78` (same sha as the commit here).

If it's not a user error, is there a better way we can debug this?

**Comment by vdice** [comment]
@bacongobbler indeed, that is the commit/tag I see when I describe a given fluentd pod:

```
    Image:      quay.io/vdice/fluentd:git-ad48f78
```

**Comment by jchauncey** [comment]
So I think some funky interaction is happening depending on where the
message comes from

**Comment by jchauncey** [comment]
So this isnt a bad fix but we can probably move it to rc1. But it does not fix the duplicate log message issue we are seeing here - https://github.com/deis/logger/issues/75

**Pull request merged**
